name: learn-github-actions
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  check-bat-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - name: Calculate time
        run: |
          started_at=$(job.started_at)
          completed_at=$(job.completed_at)

          START_TIME=$(date -d "$started_at" +%s)
          END_TIME=$(date -d "$completed_at" +%s)

          ELAPSE=$(( $END_TIME - $START_TIME ))
          TIME_TEXT="$(($ELAPSE/60))m $(($ELAPSE%60))s"
          echo "::set-output name=pr-tests::$((TIME_TEXT))"
          # - name: Pass PR Tests to "run" job
          #   id: out-step
          #   run: 
          echo "$((TIME_TEXT))"

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: 'CD5CBQ2Q6'
          # For posting a simple plain text message
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "PR <${{github.event.pull_request.html_url}}|${{github.event.number}}> by ${{github.event.pull_request.user.login}} of ${{github.event.repository.full_name}} from ${{github.event.pull_request.head.ref}} to ${{github.event.pull_request.base.ref}}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

