name: learn-github-actions
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  check-bat-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set success message color for Slack message
        if: ${{ job.status == 'success' }}
        run: echo "COLOR=#36a64f" >> $GITHUB_ENV

      - name: Set failure message color for Slack message
        if: ${{ job.status == 'failure' }}
        run: echo "COLOR=#a30301" >> $GITHUB_ENV

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: 'CD5CBQ2Q6'
          payload: |
            {
              "attachments": [
                  {
                      "mrkdwn_in": ["text"],
                      "color": "${{env.COLOR}}",
                      "text": "Post Merge result: PR <${{github.event.pull_request.html_url}}|${{github.event.number}}> by ${{github.event.pull_request.user.login}} of ${{github.event.repository.full_name}} from ${{github.event.pull_request.head.ref}} to ${{github.event.pull_request.base.ref}}"
                  }
              ]
            }

        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

